language: node_js
node_js: 
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - REDIS_SERVER="redis://127.0.0.1:6379",
  - MONGODB="mongodb://127.0.0.1:27017/test"
  - SERVER_PORT=8000
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
install: 
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
